### ISSUE TITLE
`setBuffer` can cause memory corruption, use Flex's `switch_streams` instead

### ISSUE THREAD

**Issue by fschoenberger** [kfsone/flub#1]
I was building on this project and for some very specific input files, the scanner would randomly crash (see [my StackOverflow post](https://stackoverflow.com/questions/78572719/flex-error-end-of-buffer-missed-for-very-specific-inputs)). 

I figured out that the problem stems from `setBuffer`, which can corrupt memory in very rare cases. Whenever I used address sanitizer (`-fsanitize=address`), there were issues with buffer overreads as well.

The [flex docs](https://www.cs.virginia.edu/~cr4bd/flex-manual/Cxx.html#Cxx) mention the method `switch_stream`, which can be used as a drop-in replacement for `setBuffer`:

```cpp
int Driver::parse(const char* filename)
{

    std::ifstream file(filename);
    if (!file)
    {
        std::cerr << "Failed to open file: " << filename << '\n';
        return -1;
    }

    Lexer scanner{};
    scanner.switch_streams(&file, nullptr);

    yy::Parser parse(scanner, *this);
    int res = parse();

    return res;
}
```

If needed, I can create a pull request to update the repo.

**Comment by kfsone** [comment]
Hmm - interesting; I've cleaned the project up and updated it to a CMakeLists.txt rather than a Makefile, and provided a Dockerfile.example that does nothing but run flex and bison on your files for you.

setBuffer and switch_streams do two very different things: setBuffer takes a string_view of a c-string that must outlive the lifetime of the parser (make sure you're not passing a temporary). switch_streams is for when you want the lexer to read from a file/stream for you.

That said, in the variant I'm using in-house to parse one of our grammars, for other reasons, I ended up switching from my idea of using setBuffer and mmaping files to just using switch_streams and passing it iostreams, so this probably deserves fixing.

```
	mScanner->switch_streams(file, std::cerr);
```

in your so question:

```
store(d|s|l|w|h|b) {
    yylval->emplace<StoreToken>(yytext[5]);
...
load {
    yylval->emplace<LoadToken>("d"); //FIXME
...
load(d|s|l|w|h|b|sw|uw|sh|uh|sb|ub) { 
    yylval->emplace<LoadToken>(yytext + 4); 
```

does StoreToken's constructor take a character or a pointer? LoadToken seems to take a pointer. `yytext[5]` == `*(yytext + 5)`.

**Comment by fschoenberger** [comment]
> setBuffer and switch_streams do two very different things: setBuffer takes a string_view of a c-string that must outlive the lifetime of the parser (make sure you're not passing a temporary). switch_streams is for when you want the lexer to read from a file/stream for you.

Just to check if I understood you correctly: `setBuffer` makes the lexer read from a `std::string_view`. `switch_streams` on the other hand, makes the lexer read from a different _stream_. 

Couldn't I just use [`std::stringstream` ](https://en.cppreference.com/w/cpp/io/basic_stringstream) to wrap the `string_view` and use `switch_streams` to achieve the exact same effect (or [boost iostream to avoid a copy of the buffer](https://stackoverflow.com/a/69935707/11988044)?

---

I just cloned the repo on Ubuntu 22.04 and still get errors when compiling and running with Address Sanitizer. To check this, just add `set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=address")` to your CMake Lists. In [my real project](https://github.com/fschoenberger/language-based-security/tree/dev/qbe++) I get no errors with address sanitizer.

---

> in your SO question does StoreToken's constructor take a character or a pointer? LoadToken seems to take a pointer. 

`StoreToken` takes a `char`, because the size is only one character, `LoadToken` takes a `std::string`, because the size might be longer.

```cpp
struct StoreToken {
        enum class Size : int8_t {
            kD, kS, kL, kW, kH, kB, kNone = -1      
        } size = Size::kNone;

        StoreToken() noexcept = default;

        StoreToken(char c): size([](char c) -> Size {
            switch (c) {
                case 'd': return Size::kD;
                /* omitted for brevity, you get the point. */
                case 'b': return Size::kB;
                default: throw std::runtime_error("Invalid store token");
            }
        }(c)) {}
    };

    struct LoadToken {
        enum class Size : int8_t  {kD, kS, kL, kH, kB, kSW, kUW, kSH, kUH, kSB, kUB, kNone = -1} size = Size::kNone;

        LoadToken() noexcept = default;

        LoadToken(const std::string& token) : size([](const std::string& token) -> Size {
            if (token == "d") return Size::kD;
            /* omitted for brevity, you get the point. */
            if (token == "ub") return Size::kUB;

            throw std::runtime_error("Invalid load token");
        }(token)) {}
```

(please don't judge the code too harshly, I'm by no means an expert in writing compilers.)

**Comment by kfsone** [comment]
Ah! Rats, I see the problem now:

The std::string constructor (stopped?) is stopping at the first \0 now and not including those in the std::string it allocates.

When I wrote this code, the files I was looking to parse were massive and performance was critical. I am generally distrustful of iostreams because where in principle they could be faster than c io mechanisms, the way in which formatting was added to them made them worse; when you couple in the standard streams need to synchronize with stdio the effect is pretty awful.

My intention was to mmap the files and just pass them as-is to the scanner; but I ran into memory issues as the scanner insisted on looking for extra nul bytes.

I think switching to moving the test data into a file and just using switch_streams is the right thing to do :) I'll land that in a minute.

**Comment by kfsone** [comment]
I've cleaned up a bunch, lots of documentation, but also made it read from files rather than hardcoded strings.

This version builds on mac/linux/wsl after installing essentials, but I also put the Docker example to work: the cmake lists will actually use the docker image to generate the source files.

The generated files now get placed in a "./generated" subdir rather than being in the current directory, and the CMakeLists will automatically rerun the codegen if the .ll, .y, etc files get changed.

The same CMakeLists also works on platforms that have flex/bison at hand.
